export const projects = [
    {
        title: 'Dosevana by Thrivewell',
        type: 'Website',
        img: '/images/slimup.png',
        link: 'https://www.slimupaustin.com/',
        bgClass: 'bg-blue-200',
    },
    {
        title: 'Dosevana by Thrivewell',
        type: 'Website',
        img: '/images/dosevana2.png',
        link: 'https://www.dosevana.com/',
        bgClass: 'bg-purple-200 flex justify-center',
        imgClass: 'block mx-auto',
    },
    {
        title: 'DocMedilink',
        type: 'Website',
        img: '/images/docmedicLink.png',
        link: 'https://www.docmedilink.com/',
        bgClass: 'bg-green-200',
    },
    {
        title: 'Epiq Script',
        type: 'SaaS - Health Tech',
        img: '/images/epiqScript.png',
        link: 'https://www.epiqscripts.com/',
        bgClass: 'bg-green-300',
    },
    {
        title: 'NexGen Scientific',
        type: 'Website',
        img: '/images/nexgen.png',
        link: 'https://www.nexgenmdscientific.com/',
        bgClass: 'bg-blue-300',
    },
    {
        title: 'Rizz Pharma',
        type: 'Website',
        img: '/images/ufc.png',
        link: 'https://www.rizzpharma.com/',
        bgClass: 'bg-purple-400',
    },
    {
        title: 'ThriveWellRX Web Application',
        type: 'Website',
        img: '/images/thrivewell_web.png',
        link: '',
        bgClass: 'bg-purple-400',
    },
    {
        title: 'Into Positive',
        type: 'Website',
        img: '/images/into-positive.png',
        link: '',
        bgClass: 'bg-purple-400',
    },
    {
        title: 'DocMedilink Web Application',
        type: 'Website',
        img: '/images/docmedilink-web.png',
        link: '',
        bgClass: 'bg-purple-400',
    },
    {
        title: 'Dosevana Admin Management',
        type: 'SaaS - Health Tech',
        img: '/images/dosevana-admin-management.png',
        link: '',
        bgClass: 'bg-purple-400',
    },
    {
        title: 'Dosevana QX',
        type: 'SaaS',
        img: '/images/dosevana-qx.png',
        link: '',
        bgClass: 'bg-purple-400',
    },
    {
        title: 'FlexRX',
        type: 'Website',
        img: '/images/flexrx.png',
        link: 'https://www.myflexrx.com/',
        bgClass: 'bg-purple-400',
    },
    {
        title: 'Global Travels Bangladesh',
        type: 'Website',
        img: '/images/global-travels-bangladesh.png',
        link: 'https://www.globaltravelsbd.com/',
        bgClass: 'bg-purple-400',
    },
    {
        title: 'Bio Access Labs',
        type: 'Website',
        img: '/images/bioaccess-lab.png',
        link: '',
        bgClass: 'bg-purple-400',
    },
];